name: Format
on: push
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install modules
        run: yarn --dev
      - name: Run Formatter
        run: yarn format
      - name: Config Github
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add Changes
        run: git add .

      - name: Commit Changes
        run: git commit -m "Formatting" --all | exit 0

      - name: Push Commits
        run: git push
